:twisted_rightwards_arrows: post release branch sync (#499)

diff --git a/.github/workflows/publish.yml b/.github/workflows/publish.yml
--- a/.github/workflows/publish.yml
+++ b/.github/workflows/publish.yml
@@ -68,6 +68,19 @@ jobs:
           dart pub get
           echo "IS_VERSION_GREATER=$(dart run compare_versions.dart $THIS_VERSION $BASE_VERSION_${{ matrix.package }})" >> $GITHUB_ENV
           popd || exit
+      - name: Validate pub.dev topics
+        id: validate_pub_dev_topics
+        run: |
+          set -e
+          pushd ${{ matrix.package }} || exit
+          pattern="^[a-z][a-z0-9-]*[a-z0-9]$"
+          for topic in $(yq -r '.topics[]' pubspec.yaml); do
+            if [[ ! $topic =~ $pattern ]]; then
+              echo "Invalid topic: $topic"
+              exit 1
+            fi
+          done
+          popd || exit
       - name: Set up pub credentials
         id: credentials
         if: ${{ env.IS_VERSION_GREATER == 1 }}
